server:
  port: 9090
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      username: root
      password: root
es:
  index:
    unifiedOrderIndex: data_cube_platform_order_dev_20220624
